version: '2'
services:
  battle281003:
    image: dockjulien/fake-backend:lasted
    ports:
      - "80:3000"
    links:
      - db281003
    volumes:
      - ./battleboat:/etc/backend/static
    restart: always
    environment:
      - DATABASE_HOST=db281003
      - DATABASE_PORT=3306
      - DATABASE_USER=battleuser
      - DATABASE_PASSWORD=battlepass
      - DATABASE_NAME=battleboat 
  db281003:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd281003
      - MYSQL_DATABASE=battleboat
      - MYSQL_USER=battleuser
      - MYSQL_PASSWORD=battlepass
    restart: always
    volumes:
      - mysql_config:/var/lib/mysql
volumes: 
  mysql_config:
   
   
   
   
   
    
