global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'devsecops-app'
    static_configs:
      - targets: ['devsecops-app-dev:3000', 'devsecops-app-preprod:3000', 'devsecops-app-prod:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mysql'
    static_configs:
      - targets: ['db-dev:3306', 'db-preprod:3306', 'db-prod:3306']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['dev-server-1:9100', 'dev-server-2:9100']
      - targets: ['preprod-server-1:9100', 'preprod-server-2:9100']
      - targets: ['prod-server-1:9100', 'prod-server-2:9100', 'prod-server-3:9100']
